# Generated by Django 4.2 on 2026-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
            ],
        ),
    ]
