# Generated by Django 4.2 on 2026-04-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
