# Generated by Django 4.2 on 2026-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=20)),
                ('Student_ID', models.IntegerField()),
                ('Student_Percentage', models.FloatField()),
            ],
        ),
    ]
